### ISSUE TITLE
v0.2 - pop up about benefits parametres

### ISSUE THREAD

**Issue by lisasmcdurham** [bamiesking/st-margaret#10]
Hi Ben

Sorry this is delayed, I didn't actually realise that you had released this version so only just had a chance to open it up. There's a couple of little things cropped up straight away unfortunately, but none of them look like they're breaking it necessarily.

Firstly, when clicking to create a new service user record, it brings up this box:

![image](https://user-images.githubusercontent.com/68745176/92096362-b2617a00-edce-11ea-9350-b9a5af9e08d1.png)

When I hit 'ok' or 'cancel' it goes away and brings up the 'create new' box, so it doesn't stop us doing anything, but not sure if it is a problem.

The 'create new' screen looks great, definitely resolved the issue of spacing so we can see the whole box now. The benefits tab also looks like it's going to work fine. I'll create other issue reports for the other little things.

**Comment by lisasmcdurham** [comment]
This also pops up when you have finished entering data and tab to finish. It disappears when you hit ok or cancel and brings the screen back to continue creating new records.

**Comment by bamiesking** [comment]
@lisasmcdurham can you share a screenshot of your linked tables? Like the following:

![image](https://user-images.githubusercontent.com/4366608/92327246-38402800-f050-11ea-81a5-97b163f2f9c9.png)

Additionally, ensure that when you double-click on the 'Benefits' linked table it looks like this:

![image](https://user-images.githubusercontent.com/4366608/92327261-51e16f80-f050-11ea-8726-b4d02bcc7c30.png)

The database is looking for a field called 'Benefit' in the 'Benefits' table, and that error suggests there is an issue with the back-end migration.

**Comment by lisasmcdurham** [comment]
Hi Ben

It looks like the 'benefit' column is 'outcome'.

[cid:24bf2234-7f2b-4b87-a986-dbced94a546c]

I was sure I did them all, but possibly I've missed a step somewhere?


All the best

Lisa Harrison
Deputy Manager/Finance Officer

St Margaret's Centre
The Old School, Margery Lane
Durham, DH1 4QJ
Tel: 0191 384 8100
www.stmargaretscentre.co.uk<http://www.stmargaretscentre.co.uk>
Charity no. 1060900

[cid:5dd82120-3e76-4c54-9f7d-af47f7bfaf80]

Disclaimer
The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorised to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

________________________________

**Comment by bamiesking** [comment]
Hi Lisa, 

I think I missed part of the instruction out in step 2. If you rename the 'Outcome' field to 'Benefit', then that should fix the popup issue.

**Comment by lisasmcdurham** [comment]
Fixed, thank you!
