### ISSUE TITLE
Outcomes

### ISSUE THREAD

**Issue by lisasmcdurham** [bamiesking/st-margaret#15]
Hi Ben, I hope you're doing well. Are you back in Durham now? I hope you're not locked-down!

This is less of an issue and more a question. I am currently looking at setting up our outcomes monitoring, and I need to change the outcomes categories. The question is, do I have to make these changes on the back end, or can it be done through the front end? 

And if it is the back end, is it better for me to send these to you to include in the next version release, because presumably they'll revert back to the ones that you have?

Thanks!

**Comment by bamiesking** [comment]
Hi Lisa, 

You should be able to change the outcomes categories via the front end, using the options menu (click on the St Margaret's logo in the main menu).
