### ISSUE TITLE
Benefit Types drop-down

### ISSUE THREAD

**Issue by lisasmcdurham** [bamiesking/st-margaret#4]
Hi again

I've added Benefit Types like so:
![image](https://user-images.githubusercontent.com/68745176/90881486-2f89f980-e3a2-11ea-9f6e-c38abebc50ea.png)

But the drop-down box in the Create New screen is still showing as blank:
![image](https://user-images.githubusercontent.com/68745176/90881528-43356000-e3a2-11ea-8e5b-6db8ff98a04d.png)

Wondering if there needs to be another column in the Benefits table or if the link up between the two just needs changing, as when I added Referees I first put them under 'Team', but it only showed up in the drop-down on the Create page if the info was in the 'Full Name' column.

Thanks for your help. Andrea is adding service user data now so I will let you know if there are any other little issues on the way.

**Comment by bamiesking** [comment]
Hi Lisa, in order to edit the Benefits types you need to go to the Main Menu, and then click on the St Margaret's logo to access the hidden options menu. I put it there to avoid accidental editing - if you want, I can put it in a more obvious place.

**Comment by lisasmcdurham** [comment]
Hi, I got to this screen:

![image](https://user-images.githubusercontent.com/68745176/90890743-7c75cc00-e3b2-11ea-9da1-a0d9ac9e3de0.png)

But this is just showing the benefits types I already wrote in. My issue is that it isn't linking those benefit types to the drop down box in the Generate New SU page:

![image](https://user-images.githubusercontent.com/68745176/90890916-c2329480-e3b2-11ea-90e2-c61218d94df3.png)

Can you confirm for me? 

This isn't urgent btw, please enjoy your weekend!

**Comment by bamiesking** [comment]
I see, this does look more like a bug than I thought. Can you test with the Activities/Outcomes and see whether they update?

**Comment by lisasmcdurham** [comment]
I added a test outcome category and it does display in the drop-down: 

![image](https://user-images.githubusercontent.com/68745176/90896643-e8106700-e3bb-11ea-88df-5bdcec420c38.png)

**Comment by lisasmcdurham** [comment]
Thinking about it, I think that it might be beneficial to have a tab for Benefits so it is possible to select multiple types and input info on review dates etc. Will discuss this with Andrea on Monday.
