### ISSUE TITLE
Add two boxes to Create New 

### ISSUE THREAD

**Issue by lisasmcdurham** [bamiesking/st-margaret#5]
It would be helpful to have two boxes in the Create New screen for 'Care Coordinator' and 'Care Coordinator Phone Number' (or 'CC Phone Number' if it is better for spacing').

I'm aware I just asked you to reduce the size of that window and then to add two boxes, so my solution would be to add those in place of 'Dependants' and 'Marital Status', which are less useful to us, if that isn't too much trouble.

Thanks again.

**Comment by bamiesking** [comment]
No problem. If possible, now that you've had some time to work with the database, a detailed breakdown of which fields should always be visible and which could live inside a tabbed box would very helpful - I decided what goes where very arbitrarily so it would be great to hear your thoughts.

**Comment by lisasmcdurham** [comment]
I'll chat with Andrea more on Monday as she'll be using these screens the most, and we'll have a good look at it. Thank you!
