### ISSUE TITLE
Transfer benefits fields to new tab

### ISSUE THREAD

**Issue by bamiesking** [bamiesking/st-margaret#6]
Thinking about it, I think that it might be beneficial to have a tab for Benefits so it is possible to select multiple types and input info on review dates etc. Will discuss this with Andrea on Monday.

_Originally posted by @lisasmcdurham in https://github.com/bamiesking/st-margaret/issues/4#issuecomment-678295875_

**Comment by lisasmcdurham** [comment]
Hi Ben

I've spoken about it with Andrea and she agrees it would be helpful to have this as a tab, same as referees where benefits can be selected from a box, a date box for when they were put in place, and a notes box so she can type info on the next review etc. Thank you.

**Comment by bamiesking** [comment]
No problem. This will require you to make some changes to the back-end, however I'll set these out clearly in a wiki page.
