### ISSUE TITLE
Tabbed boxes, visible fields

### ISSUE THREAD

**Issue by lisasmcdurham** [bamiesking/st-margaret#7]
No problem. If possible, now that you've had some time to work with the database, a detailed breakdown of which fields should always be visible and which could live inside a tabbed box would very helpful - I decided what goes where very arbitrarily so it would be great to hear your thoughts.

_Originally posted by @bamiesking in https://github.com/bamiesking/st-margaret/issues/5#issuecomment-678263404_

Hi, we had a look and alongside the benefits tab that is in another issue, I think the following would be good:

- Changing marital status and dependants to 'Care Coordinator' and 'Care Coordinator Contact Number' - both write-in boxes
- Removing the 'Interests and Hobby Info' box entirely, putting the drop-down 'Area of Interest' box to 'Other Info'.

Finally, a minor thing that makes absolutely no difference to me... Andrea asked if it possible to show each attachment in the attachment box, rather than just having the single file in the middle that you can double-click to see the attachments. She would like it to look like one of her Windows folders where she can see them all. I told her she was being extra, which she admitted, but I'd ask anyway. Don't worry if this isn't possible!

**Comment by bamiesking** [comment]
No problem. Again, the two bullet points will require small changes to the back-end. I'll create a new issue for the attachments request, as it should be possible but I will leave it until I have addressed other issues.

**Comment by lisasmcdurham** [comment]
Thanks Ben. I hope you have a good week.
